apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rcl-platform

bases:
  - ../base

configMapGenerator:
  - name: rcl-config
    behavior: merge
    literals:
      - NODE_ENV=staging
      - CORS_ORIGIN=https://admin-staging.rcl.io,https://store-staging.rcl.io

replicas:
  - name: api-gateway
    count: 2
  - name: auth-service
    count: 2
  - name: product-service
    count: 2
  - name: order-service
    count: 2
  - name: payment-service
    count: 2
  - name: inventory-service
    count: 2
  - name: notification-service
    count: 2
  - name: admin-nextjs
    count: 2
  - name: storefront-nextjs
    count: 2
  - name: marketing-service
    count: 2
  - name: logistics-service
    count: 2
