apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rcl-platform

resources:
  - 00-namespace-config.yaml
  - 01-auth-db.yaml
  - 02-redis.yaml
  - 03-rabbitmq.yaml
  - 04-api-gateway.yaml
  - 05-auth-service.yaml
  - 06-payment-db.yaml
  - 07-product-service.yaml
  - 08-order-service.yaml
  - 09-payment-service.yaml

commonLabels:
  app.kubernetes.io/part-of: rcl-platform
  app.kubernetes.io/managed-by: kustomize
